# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Funny Changes 🛠
      labels:
        - funny-Major
        - funny-change
    - title: Silly New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: More funny Changes
      labels:
        - "*"
